#!/bin/bash

mysqldump \
  -h "$DB_HOST" \
  -P "$DB_PORT" \
  -u "$DB_USER" \
  --password="$DB_PASS" \
  "$DB_NAME" \
  --no-data \
    > /opt/sql/db.sql

mysqldump \
  --extended-insert=FALSE \
  -h "$DB_HOST" \
  -P "$DB_PORT" \
  -u "$DB_USER" \
  --password="$DB_PASS" \
  "$DB_NAME" \
  --no-create-info \
  --ignore-table="$DB_NAME".cache \
  --ignore-table="$DB_NAME".cache_admin_menu \
  --ignore-table="$DB_NAME".cache_block \
  --ignore-table="$DB_NAME".cache_bootstrap \
  --ignore-table="$DB_NAME".cache_field \
  --ignore-table="$DB_NAME".cache_filter \
  --ignore-table="$DB_NAME".cache_form \
  --ignore-table="$DB_NAME".cache_menu \
  --ignore-table="$DB_NAME".cache_page \
  --ignore-table="$DB_NAME".cache_path \
  --ignore-table="$DB_NAME".cache_update \
  --ignore-table="$DB_NAME".watchdog \
    >> /opt/sql/db.sql
